/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.sistemkehadiranpegawai;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SYAUQI
 */
public class AdminDashboard extends javax.swing.JFrame {

    /** Creates new form AdminDashboard */
    public AdminDashboard() {
        initComponents();
    
    // Header tabel sesuai gambar kamu
    String[] kolom = {"NIP", "Nama", "Jabatan", "Departemen"};
    DefaultTableModel model = new DefaultTableModel(kolom, 0);
    
    // Menghubungkan model ke tabel
    tblKaryawan.setModel(model); 
    
    // Menambah data contoh agar tidak kosong
    model.addRow(new Object[]{"2025001", "Syauqi", "Admin", "IT"});
    
    // Pengaturan Tabel Departemen
String[] kolomDept = {"ID Departemen", "Nama Departemen"};
DefaultTableModel modelDept = new DefaultTableModel(kolomDept, 0);
tblDepartemen.setModel(modelDept); // Menghubungkan ke variabel tblDepartemen

// Menambah data awal sebagai contoh
modelDept.addRow(new Object[]{"D01", "IT"});
modelDept.addRow(new Object[]{"D02", "HRD"});
modelDept.addRow(new Object[]{"D03", "Finance"});

// Header untuk tabel kehadiran
String[] kolomHadir = {"Tanggal", "NIP", "Nama", "Status"};
DefaultTableModel modelHadir = new DefaultTableModel(kolomHadir, 0);

// Menghubungkan ke tabel di Design (Pastikan nama variabelnya tblKehadiran)
tblKehadiran.setModel(modelHadir); 

// Data contoh agar tabel tidak kosong saat dibuka
modelHadir.addRow(new Object[]{"2025-12-18", "2025001", "Syauqi", "Hadir"});
modelHadir.addRow(new Object[]{"2025-12-18", "2025002", "Budi", "Pending"});
    


    setLocationRelativeTo(null); // Memunculkan aplikasi di tengah layar
    
    // --- TARUH KODE HELPER DI SINI (SEBELUM KURUNG TERAKHIR) ---
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDepartemen = new javax.swing.JTable();
        btnTambah1 = new javax.swing.JButton();
        btnEditDept = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKehadiran = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDepartemen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Departemen", "Nama Departemen"
            }
        ));
        jScrollPane2.setViewportView(tblDepartemen);

        btnTambah1.setText("Tambah");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnEditDept.setText("Edit");
        btnEditDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDeptActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnTambah1)
                .addGap(37, 37, 37)
                .addComponent(btnEditDept)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah1)
                    .addComponent(btnEditDept)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Kelola Departemen", jPanel1);

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Jabatan", "Departemen"
            }
        ));
        jScrollPane1.setViewportView(tblKaryawan);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnTambah)
                .addGap(39, 39, 39)
                .addComponent(btnEdit)
                .addGap(36, 36, 36)
                .addComponent(btnHapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Kelola Karyawan", jPanel2);

        tblKehadiran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "NIP", "Nama", "Status"
            }
        ));
        jScrollPane3.setViewportView(tblKehadiran);

        jButton2.setText("Konfirmasi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Kehadiran", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
JTextField nipField = new JTextField();
    JTextField namaField = new JTextField();
    
    // Dropdown Jabatan
    String[] jabatan = {"Staff", "Manager", "Admin"};
    JComboBox<String> jabatanCombo = new JComboBox<>(jabatan);
    
    // Dropdown Departemen (Baru)
    String[] departemen = {"IT", "HRD", "Finance", "Marketing"};
    JComboBox<String> deptCombo = new JComboBox<>(departemen);

    Object[] inputFields = {
        "NIP:", nipField,
        "Nama:", namaField,
        "Jabatan:", jabatanCombo,
        "Departemen:", deptCombo // Menambahkan pilihan departemen
    };

    int option = JOptionPane.showConfirmDialog(this, inputFields, "Tambah Karyawan Baru", JOptionPane.OK_CANCEL_OPTION);
    
    if (option == JOptionPane.OK_OPTION) {
        DefaultTableModel model = (DefaultTableModel) tblKaryawan.getModel();
        model.addRow(new Object[]{
            nipField.getText(), 
            namaField.getText(), 
            jabatanCombo.getSelectedItem().toString(), 
            deptCombo.getSelectedItem().toString() // Mengambil hasil pilihan user
        });
    }      // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
int row = tblKaryawan.getSelectedRow(); // Mengambil baris yang dipilih user
    if (row != -1) {
        DefaultTableModel model = (DefaultTableModel) tblKaryawan.getModel();
        model.removeRow(row); // Menghapus data dari tabel
        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris di tabel dulu!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
// 1. Cek apakah ada baris yang dipilih di tabel
    int row = tblKaryawan.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
        return;
    }

    // 2. Ambil data lama dari tabel untuk ditampilkan di form
    DefaultTableModel model = (DefaultTableModel) tblKaryawan.getModel();
    String nipLama = model.getValueAt(row, 0).toString();
    String namaLama = model.getValueAt(row, 1).toString();
    String jabatanLama = model.getValueAt(row, 2).toString();
    String deptLama = model.getValueAt(row, 3).toString();

    // 3. Siapkan komponen Input dengan data lama
    JTextField nipField = new JTextField(nipLama);
    JTextField namaField = new JTextField(namaLama);
    
    String[] daftarJabatan = {"Staff", "Manager", "Admin"};
    JComboBox<String> jabatanCombo = new JComboBox<>(daftarJabatan);
    jabatanCombo.setSelectedItem(jabatanLama);

    String[] daftarDept = {"IT", "HRD", "Finance", "Marketing"};
    JComboBox<String> deptCombo = new JComboBox<>(daftarDept);
    deptCombo.setSelectedItem(deptLama);

    Object[] inputFields = {
        "NIP:", nipField,
        "Nama:", namaField,
        "Jabatan:", jabatanCombo,
        "Departemen:", deptCombo
    };

    // 4. Tampilkan Dialog Konfirmasi
    int option = JOptionPane.showConfirmDialog(this, inputFields, "Edit Data Karyawan", JOptionPane.OK_CANCEL_OPTION);
    
    if (option == JOptionPane.OK_OPTION) {
        // 5. Update data di tabel dengan input baru
        model.setValueAt(nipField.getText(), row, 0);
        model.setValueAt(namaField.getText(), row, 1);
        model.setValueAt(jabatanCombo.getSelectedItem().toString(), row, 2);
        model.setValueAt(deptCombo.getSelectedItem().toString(), row, 3);
        
        JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui!");
    }       // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
JTextField idField = new JTextField();
    JTextField namaField = new JTextField();

    Object[] inputFields = {
        "ID Departemen:", idField,
        "Nama Departemen:", namaField
    };

    int option = JOptionPane.showConfirmDialog(this, inputFields, "Tambah Departemen", JOptionPane.OK_CANCEL_OPTION);
    
    if (option == JOptionPane.OK_OPTION) {
        DefaultTableModel model = (DefaultTableModel) tblDepartemen.getModel(); // Mengambil model tblDepartemen
        model.addRow(new Object[]{idField.getText(), namaField.getText()});
        JOptionPane.showMessageDialog(this, "Departemen Berhasil Ditambahkan!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnEditDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDeptActionPerformed
int row = tblDepartemen.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih departemen yang ingin diedit!"); // Validasi klik tabel
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblDepartemen.getModel();
    JTextField idField = new JTextField(model.getValueAt(row, 0).toString());
    JTextField namaField = new JTextField(model.getValueAt(row, 1).toString());

    Object[] inputFields = {"ID Departemen:", idField, "Nama Departemen:", namaField};

    int option = JOptionPane.showConfirmDialog(this, inputFields, "Edit Departemen", JOptionPane.OK_CANCEL_OPTION);
    if (option == JOptionPane.OK_OPTION) {
        model.setValueAt(idField.getText(), row, 0); // Update baris yang dipilih
        model.setValueAt(namaField.getText(), row, 1);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditDeptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int row = tblKehadiran.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris di tabel kehadiran dulu!");
        return;
    }

    String[] pilihanStatus = {"Hadir", "Izin", "Sakit", "Alpa"};
    JComboBox<String> statusCombo = new JComboBox<>(pilihanStatus);
    
    // Ambil status lama dari tabel (kolom indeks 3)
    statusCombo.setSelectedItem(tblKehadiran.getValueAt(row, 3).toString());

    int option = JOptionPane.showConfirmDialog(this, statusCombo, "Update Status Kehadiran", JOptionPane.OK_CANCEL_OPTION);
    
    if (option == JOptionPane.OK_OPTION) {
        tblKehadiran.setValueAt(statusCombo.getSelectedItem().toString(), row, 3);
        JOptionPane.showMessageDialog(this, "Status Berhasil Diperbarui!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditDept;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDepartemen;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTable tblKehadiran;
    // End of variables declaration//GEN-END:variables

}
