/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author lenovo
 */
import javax.swing.*;
import java.awt.*;

public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JButton btnLogin;
            
    public LoginForm() {
        initComponents();
        setTitle("Login");
        setSize(400, 450); 
        setLocationRelativeTo(null);
        initCustomComponents();    // TAMBAHAN KITA
        setupEvent();  
    }

     // ===== KOMPONEN BUATAN SENDIRI =====
private void initCustomComponents() {

    JPanel panel = new JPanel(new GridBagLayout());
    panel.setBackground(Color.WHITE);

    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(8, 20, 8, 20);
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.weightx = 1;

    JLabel lblTitle = new JLabel("LOGIN");
    lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 22));
    lblTitle.setHorizontalAlignment(SwingConstants.CENTER);

    JLabel lblUsername = new JLabel("Username");
    JLabel lblPassword = new JLabel("Password");

    txtUsername = new JTextField();
    txtPassword = new JPasswordField();
    btnLogin = new JButton("Login");

    // ukuran input
    txtUsername.setPreferredSize(new Dimension(280, 38));
    txtPassword.setPreferredSize(new Dimension(280, 38));
    btnLogin.setPreferredSize(new Dimension(280, 42));

    btnLogin.setBackground(new Color(33, 150, 243));
    btnLogin.setForeground(Color.WHITE);

    // ===== TITLE =====
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 1;
    panel.add(lblTitle, gbc);

    // ===== USERNAME =====
    gbc.gridy++;
    panel.add(lblUsername, gbc);

    gbc.gridy++;
    panel.add(txtUsername, gbc);

    // ===== PASSWORD =====
    gbc.gridy++;
    panel.add(lblPassword, gbc);

    gbc.gridy++;
    panel.add(txtPassword, gbc);

    // ===== BUTTON =====
    gbc.gridy++;
    gbc.insets = new Insets(20, 20, 10, 20);
    panel.add(btnLogin, gbc);

    setContentPane(panel);
}

    // ===== EVENT =====
    private void setupEvent() {
        btnLogin.addActionListener(e -> loginAction());
    }

    private void loginAction() {
        if (txtUsername.getText().isEmpty()
                || String.valueOf(txtPassword.getPassword()).isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Username dan Password harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            // PINDAH KE MENU
            MenuForm menu = new MenuForm();
            menu.setVisible(true);
            this.dispose(); // tutup login
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
